2021-09-12 16:38:18,920 ERROR: Exception on /search [GET] [in c:\code\personal\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Code\Personal\microblog\app\main\routes.py", line 159, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "C:\Code\Personal\microblog\app\models.py", line 88, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "C:\Code\Personal\microblog\app\search.py", line 20, in query_index
    search = current_app.elasticsearch.search(
  File "c:\code\personal\microblog\venv\lib\site-packages\elasticsearch\client\utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "c:\code\personal\microblog\venv\lib\site-packages\elasticsearch\client\__init__.py", line 1668, in search
    return self.transport.perform_request(
  File "c:\code\personal\microblog\venv\lib\site-packages\elasticsearch\transport.py", line 458, in perform_request
    raise e
  File "c:\code\personal\microblog\venv\lib\site-packages\elasticsearch\transport.py", line 419, in perform_request
    status, headers_response, data = connection.perform_request(
  File "c:\code\personal\microblog\venv\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 277, in perform_request
    self._raise_error(response.status, raw_data)
  File "c:\code\personal\microblog\venv\lib\site-packages\elasticsearch\connection\base.py", line 330, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2021-09-12 16:43:49,085 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:77]
2021-09-12 16:47:03,350 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:77]
2021-09-12 16:49:47,510 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:77]
2021-09-12 16:53:00,867 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:77]
2021-09-12 17:05:59,478 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:77]
2021-09-12 17:07:57,801 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:77]
2021-09-12 17:08:14,369 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:77]
2021-09-12 17:09:12,191 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:77]
2021-09-12 17:09:14,322 ERROR: Exception on /index [GET] [in c:\code\personal\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Code\Personal\microblog\app\main\routes.py", line 44, in index
    return render_template('index.html', title=_('Home'), form=form,
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\code\personal\microblog\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "c:\code\personal\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\Personal\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Code\Personal\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'body'
    {% block navbar %}
  File "C:\Code\Personal\microblog\app\templates\base.html", line 27, in block 'navbar'
    {{ g.search_form.q(size=20, class='form-control', placeholder=g.search_form.q.label.text) }}
  File "c:\code\personal\microblog\venv\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'flask.ctx._AppCtxGlobals object' has no attribute 'search_form'
2021-09-12 17:10:03,938 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:77]
2021-09-12 19:50:03,955 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:82]
