2021-09-12 15:38:34,560 ERROR: Exception on /index [GET] [in c:\code\personal\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "C:\Code\Personal\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
TypeError: user() missing 1 required positional argument: 'username'
2021-09-12 15:39:13,804 ERROR: Exception on /index [GET] [in c:\code\personal\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "C:\Code\Personal\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
TypeError: user() missing 1 required positional argument: 'username'
2021-09-12 15:39:25,785 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:73]
2021-09-12 15:39:26,086 ERROR: Exception on /index [GET] [in c:\code\personal\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "C:\Code\Personal\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
TypeError: user() missing 1 required positional argument: 'username'
2021-09-12 15:40:38,611 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:73]
2021-09-12 15:41:07,284 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:73]
2021-09-12 15:41:13,628 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:73]
2021-09-12 15:41:17,168 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:73]
2021-09-12 15:41:18,462 ERROR: Exception on /index [GET] [in c:\code\personal\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "C:\Code\Personal\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
TypeError: user() missing 1 required positional argument: 'username'
2021-09-12 15:42:30,803 ERROR: Exception on /index [GET] [in c:\code\personal\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "C:\Code\Personal\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
TypeError: user() missing 1 required positional argument: 'username'
2021-09-12 15:44:53,020 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:74]
2021-09-12 16:19:48,938 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:77]
2021-09-12 16:19:51,815 ERROR: Exception on /index [GET] [in c:\code\personal\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Code\Personal\microblog\app\main\routes.py", line 45, in index
    return render_template('index.html', title=_('Home'), form=form,
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\code\personal\microblog\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "c:\code\personal\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\Personal\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\code\personal\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\Personal\microblog\app\templates\base.html", line 43, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2021-09-12 16:20:47,991 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:77]
